services:
  mongo-express-qabots:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081
    environment:
      # Use the Service Name of your MongoDB in Dokploy
      - ME_CONFIG_MONGODB_SERVER=qabots-mongo-yfltet
      - ME_CONFIG_MONGODB_PORT=27017
      # Database Credentials
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pioutfwm5dg5tx1l
      # Web UI Credentials (Login page)
      - ME_CONFIG_BASICAUTH_USERNAME=admin-y67yu8i1h
      - ME_CONFIG_BASICAUTH_PASSWORD=^SOE7^aUnSx6705T79dHl5
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:pioutfwm5dg5tx1l@qabots-mongo-yfltet:27017/?authSource=admin
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
